stages:
  - build
  - deploy

build_job:
  stage: build
  tags:
   - t.pt.miui.com
  before_script:
    - npm ci
  script:
    ## 用于构建项目的分支或tag名称
    - ./build.sh $CI_COMMIT_REF_NAME
    - echo 'test 名称'
    - echo $CI_COMMIT_REF_SLUG
    - echo 'majunchang'
    - echo $CI_COMMIT_REF_NAME
  artifacts:
    name: $CI_COMMIT_REF_SLUG
    paths:
      - dist
    expire_in: 10 yrs
  only:
    refs:
      - master
  when: always


deploy_dev_job:
  stage: deploy
  tags:
    - t.pt.miui.com
  script:
    - curl "http://tj1-miui-bw-stage000.kscn:8090/?shell=/home/work/CI_CD/gitlab_cd.fe.sh&param1=/home/work/staging-webroot/mifeeds-mobile-v2&param2=$CI_COMMIT_TAG"
  environment:
    # 定义一个job(作业)部署到某个具名的环境
    name: dev
    url: "http://feed.dev.browser.miui.com/mobile-v2/"
  only:
    - /^dev_/
  except:
    - branches
  when: manual

